version: 2.1

orbs:
  android: circleci/android@1.0.0

jobs:
  build:
    executor: android/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
      - run:
          name: Build and test
          command: ./gradlew clean build test

      - store_artifacts:
          path: app/build/outputs/apk/debug
          destination: artifacts
